#!/bin/bash

[[ "$#" -gt 0 && "$#" -lt 3 ]] || { echo "Usage: $(basename $0) email [alertThreshold]" >&2; exit 1; }

email=${1}
alertThreshold=${2-98}

process() {
	while read filesystem size used free usedPercentage mnt ;
	do
		if [[ $(echo ${usedPercentage} | tr -d '%') -ge ${alertThreshold} ]]; then
			message="${message}\n---\nFilesystem: ${filesystem}\nMount: ${mnt}\nUsed: $used (${usedPercentage})\nFree: ${free}"
		fi
	done

	if [[ -n "${message}" ]]; then
		host=$(hostname --fqdn)
		echo -e "Low storage space!\n\nHost: ${host}\nDate: $(date)\nAlert Threshold: ${alertThreshold}%${message}" \
			| tee >(mail -s "Low storage space on ${host}" ${email})
	fi
}

df -HP | grep -vE '^Filesystem|cdrom|tmpfs' | process
